### PR TITLE
fix chat auth after a signout->signin.

### LINKED ISSUE #131: chat: fix authentication when user signs-out then an other user signs in
If you sign out then signin to an other user without reloading the page, the chat still believes the previous user is connected.

### PR DESCRIPTION
**Pull request by ecogest**
Connect the proper user to the chat after a signout/signin.
closes #131

### CODE REVIEW

**Review by luweglarz — COMMENTED** [review]
I am getting an invalid token error when I open the chat interface
Screenshot 2022-09-15 at 12 02 03

**Comment by ecogest** [comment]
> I am getting an invalid token error when I open the chat interface
OK merci, je check ça !

**Comment by luweglarz** [comment]
After restarting the containers I can't get the error again, It happened at my first connection right after the containers were up, but now it seems to be good.

**Review by luweglarz — APPROVED** [review]
LGTM

**Pull request merged**
