### PR TITLE
Chat

### PR DESCRIPTION
**Pull request by jchemoun**
Invites to rooms working
"/invite USERNAME" to invite it in the room

### CODE REVIEW

**Comment by luweglarz** [comment]
I think it would be better if when you invite an user into your protected room that they don't need to type the password of the room

**Comment by jchemoun** [comment]
> I think it would be better if when you invite an user into your protected room that they don't need to type the password of the room, otherwise LGTM.

I prefer it this way.

**Review by luweglarz — APPROVED** [review]

**Review by S-i-d-V — APPROVED** [review]
Seems good to me.
But i dont really understand how the private rooms works, what's the difference with normal rooms ?
The chat don't take the entire space available (in width) too.

**Comment by jchemoun** [comment]
> Seems good to me. But i dont really understand how the private rooms works, what's the difference with normal rooms ? The chat don't take the entire space available (in width) too.

For now private rooms act like public one, next pr is gonna be on that

**Pull request merged**
