### PR TITLE
Chat

### PR DESCRIPTION
**Pull request by jchemoun**
Command with / in chat room,
/admin USERNAME
/deadmin USERNAME
/password remove
/password change NEW_PASSWORD

### CODE REVIEW

**Comment by ecogest** [comment]
Password change is not taken into account when I remove the password before changing it. Neither when I create a public room and change password afterwards.

**Comment by ecogest** [comment]
What is `/admin username` supposed to do ? (I can't see any change, even in the db)

**Comment by ecogest** [comment]
Btw, it would be nice to have some feedback when a command succeed or fails, at least with console.log/console.error for now (and directly in the chatbar later). Simple messages would make debugging much easier (for example stuff like `password successfully changed in room RoomName` / `cannot change password in room roomName because ...` / `user userName is now admin of room roomName` / `command does not exist` etc.).

**Review by S-i-d-V — COMMENTED** [review]
I agree with Mathieu for the feedbacks when a command succeeds or not. Like a message  that can be see only by the sender of the command ( in another color maybe ).

I think it could be cool to have a dedicated button or command to leave a room without joining or creating another one.

**Comment by luweglarz** [comment]
Except the rooms that diseappear when I create a new one and the other points told above it looks good to me 👍

**Comment by jchemoun** [comment]
> Password change is not taken into account when I remove the password before changing it. Neither when I create a public room and change password afterwards.

Removing a password from a protected room change the protected room into a public one, you currenctly cannot add a password to a public room nor is it required in the subject

**Comment by jchemoun** [comment]
> I agree with Mathieu for the feedbacks when a command succeeds or not. Like a message that can be see only by the sender of the command ( in another color maybe ).

feedback is planned directly in the chat room and only visible to the user who typed the command

**Comment by jchemoun** [comment]
> I think it could be cool to have a dedicated button or command to leave a room without joining or creating another one.

Good idea, i will do that

**Comment by jchemoun** [comment]
> Except the rooms that diseappear when I create a new one and the other points told above it looks good to me 👍

Creating a room makes you leave the room you were in; if no users are present in the room it is automaticly removed

**Comment by jchemoun** [comment]
> image
> Not sure why, but sometimes an empty room automatically disappears, sometimes it does not (here I have two users in room `abc`, none in room `hello`: but room `hello` remains visible)

This is a bug, how did you managed to do that ?

**Review by ecogest — APPROVED** [review]
Nice 👍 !

**Review by S-i-d-V — APPROVED** [review]
Seems good to me 👍

**Review by luweglarz — APPROVED** [review]
LGTM

**Pull request merged**
