### PR TITLE
Social popup

### PR DESCRIPTION
**Pull request by S-i-d-V**
Implementation of list of friends/blocked users.

### CODE REVIEW

**Comment by S-i-d-V** [comment]
The ingame status is working fine and the spectate button moved to the social popup !

**Comment by ecogest** [comment]
Nice :) ! Still, at least one issue: if a friend reloads it's page, he will then appear as offline.

**Comment by luweglarz** [comment]
The issue come from the fact that the client doesn't reconnect after a reload of the page, I manage to fix it(The same bug happened when a friend was in game and I fixed it too)

**Comment by ecogest** [comment]
I just moved a few subscriptions, inside the StatusSocket class so that:
- we don't subscribe multiple times to the same events
- the status is actualised live in the friend page (no need to close and reopen page to see status change)

**Comment by ecogest** [comment]
The friendlist is not updated if a friend changes it's username. I look into it.

**Comment by luweglarz** [comment]
Apparently you can add the new username and it will keep the old one into your friendlist

**Comment by ecogest** [comment]
> The friendlist is not updated if a friend changes it's username. I look into it.

Fixed by 8b5b3c5 . The username is refreshed as soon as the social component is reloaded (ex: close and reopen the social popup).

**Review by ecogest — APPROVED** [review]
LGTM!

**Pull request merged**
