### PR TITLE
Chat

### PR DESCRIPTION
**Pull request by jchemoun**
ban and mute users done

### CODE REVIEW

**Comment by ecogest** [comment]
`/ban` is currently doing a mute. It would also be nice if the banned/muted user had a popup message saying that he is banned/muted if he tries to enter the room or write a message.
ban-mute

**Comment by jchemoun** [comment]
> `/ban` is currently doing a mute. It would also be nice if the banned/muted user had a popup message saying that he is banned/muted if he tries to enter the room or write a message. ban-mute [ ban-mute ](https://user-images.githubusercontent.com/29286000/185928715-39b6a08d-5659-40d2-85b2-b2142c33f845.gif) [ ](https://user-images.githubusercontent.com/29286000/185928715-39b6a08d-5659-40d2-85b2-b2142c33f845.gif)

/ban forbid the user from sending and receiving messages, i'll fix the typo and add a popup for the banned/muted user

**Comment by ecogest** [comment]
> /ban forbid the user from sending and receiving messages, i'll fix the typo and add a popup for the banned/muted user

As I understand it, a banned user is a user that has been kicked out of the room and that he can't rejoin the room as long as the ban lasts (hence he can't see old messages from that room either). But of course, I could be wrong (and maybe both approaches are accepted). What do you think @jchemoun @luweglarz @S-i-d-V  ?

**Comment by jchemoun** [comment]
> > /ban forbid the user from sending and receiving messages, i'll fix the typo and add a popup for the banned/muted user
> 
> As I understand it, a banned user is a user that has been kicked out of the room and that can't rejoin the room as long as the ban lasts (hence he can't see old messages from that room either). But of course, I could be wrong (and maybe both approaches are accepted). What do you think @jchemoun @luweglarz @S-i-d-V ?

As i implemented it, a banned user is still in the room but cannot receive or send new messages. If you want a kick and him not being able to see the room is possible.

**Review by ecogest — APPROVED** [review]
It's now working as you describe 👍 I still think that it would have been preferable to really kick a banned user out of the room, but I guess your way is fine too.

**Pull request merged**
