### PR TITLE
Invitation to a private game

### LINKED ISSUE #124: Game invitation
A user should be able to invite another user to play a private game together

### PR DESCRIPTION
**Pull request by luweglarz**
closes #124

### CODE REVIEW

**Comment by ecogest** [comment]
For now I don't see anything happening on the challenged player side
challenge

**Comment by S-i-d-V** [comment]
> For now I don't see anything happening on the challenged player side challenge [ challenge ](https://user-images.githubusercontent.com/29286000/190184655-064c470a-1e77-4450-9056-94737b2d869a.gif) [ ](https://user-images.githubusercontent.com/29286000/190184655-064c470a-1e77-4450-9056-94737b2d869a.gif)

Oui need to click on the bell at the bottom right corner of the chat and accept the invite

**Review by S-i-d-V — APPROVED** [review]
Everything working for me ! 👍 
I will add some style to the waiting screen in another PR.

**Comment by ecogest** [comment]
> > For now I don't see anything happening on the challenged player side
> 
> You need to click on the bell at the bottom right corner of the chat and accept the invite

Indeed, good for me too then !

**Pull request merged**
