### PR TITLE
Ladderboard popUps

### PR DESCRIPTION
**Pull request by S-i-d-V**

### CODE REVIEW

**Comment by S-i-d-V** [comment]
Had to fix some backend lint errors, i fixed it (I'm 99% sure my change doesnt change anything in the code).
It's on chat.gateway, some variables weren't used for so i did a little changed.

**Comment by S-i-d-V** [comment]
Later, i will make a dedicated module for the buttons that pop when the user hover an username to reuse it on profil and social.

**Review by ecogest — APPROVED** [review]
Very nice 👍

**Review by luweglarz — APPROVED** [review]
LGTM

**Pull request merged**
